# Generated by Django 5.2.2 on 2025-06-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('duration', models.IntegerField(help_text='Duração do serviço em minutos')),
                ('price', models.CharField(help_text='Preço em reais', max_length=20)),
            ],
        ),
    ]
