# Generated by Django 5.2.2 on 2025-06-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created_by',
        ),
    ]
