# Generated by Django 5.2.2 on 2025-07-25 18:49

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[],
            options={
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("EMPLOYEE", "Funcionário"),
                    ("PROFESSIONAL", "Profissional"),
                ],
                default="EMPLOYEE",
                max_length=12,
            ),
        ),
    ]
