# Generated by Django 5.2.2 on 2025-07-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_professional_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="employee",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("role", "EMPLOYEE"), ("role", "PROFESSIONAL"), _connector="OR"
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Funcionário",
            ),
        ),
    ]
