# Generated by Django 5.2.2 on 2025-06-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_username_appointment_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='collaborator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.collaborator'),
        ),
    ]
