# Generated by Django 5.2.2 on 2025-07-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_appointment_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
    ]
