# Generated by Django 5.2.2 on 2025-06-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appointment_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='collaborator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
