# Generated by Django 5.2.2 on 2025-06-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_appointment_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(help_text='Preço em reais'),
        ),
    ]
