# Generated by Django 5.2.2 on 2025-06-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='phone',
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
