# Generated by Django 5.2.2 on 2025-06-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_collaborator_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
