# Generated by Django 5.2.2 on 2025-06-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='collaborator',
            new_name='professional',
        ),
    ]
